### ISSUE TITLE
Monitoring and logging integration for k8s clusters

### ISSUE THREAD

**Issue by brandisimus** [oxheadalpha/tezos-k8s#112]
Integrate Prometheus/Grafana logging and monitoring into the toolchain such that it should be possible:
 * at the chain creation time enable/not logging and monitoring
 * add logging and monitoring to the running cluster

**Comment by harryttd** [comment]
Cloudwatch logging was implemented in tqinfra https://github.com/tqtezos/tqinfra/pull/27 https://github.com/tqtezos/tqinfra/pull/47

**Comment by elric1** [comment]
PR #236 also adds cloudwatch support in the pulumi code in tezos-k8s.
PR #209 adds a metrics container which can be integrated with Prometheus/Grafana
PR #209 adds a logger container which outputs some interesting logs

**Comment by harryttd** [comment]
Look into k8s cluster auditing
https://kubernetes.io/docs/tasks/debug-application-cluster/audit/
https://www.datadoghq.com/blog/monitor-kubernetes-audit-logs/

**Comment by harryttd** [comment]
We now expose the metrics endpoint of nodes. Closing this as really it is relevant to where we deploy our clusters.
