### ISSUE TITLE
Ability to run nodes with different docker images

### ISSUE THREAD

**Issue by brandisimus** [oxheadalpha/tezos-k8s#113]
A user should be able to chose a number of nodes running specific versions of protocols and simulate the a protocol upgrade.

**Comment by elric1** [comment]
@nicolasochem has provided the ability to upgrade protocols. This requires an image that supports both protocols, but this is standard.
Do we want to be able to simulate a mixed network? I can easily add this my `name-the-nodes` branch. The branch lets you define new stateful sets which are named and fire up nodes in a configurable way. It would be easy enough to specify a different image for each statefulset if we think that would be useful? I think that it may very well be useful for testing upgrades when a certain percentage of the nodes haven't bothered to upgrade, e.g.

**Comment by harryttd** [comment]
duplicate of #226
