### ISSUE TITLE
Utils docker image build is really slow

### ISSUE THREAD

**Issue by harryttd** [oxheadalpha/tezos-k8s#317]
The amount of time it takes is especially a problem with deploying code to our infra. We have tried to utilize a caching mechanism in pulumi. It doesn't completely work as of yet. But I wanted to put some articles in here for future reference that have some ideas about how to make our python base image build faster.

We should investigate:
- different python base images
- parallel pip package installs. We currently have many lines all running separate pip install cmds.

https://pythonspeed.com/articles/alpine-docker-python/
https://stackoverflow.com/questions/26228136/pip-build-option-to-use-multicore

**Comment by elric1** [comment]
I think that PR#362 and its fix PR#366 address this issue?

**Comment by harryttd** [comment]
Closing issue. Removing numpy significantly reduced the build time.
