### ISSUE TITLE
Snapshot downloader: Check for node's history mode only looks at the config on the node instance level

### ISSUE THREAD

**Issue by harryttd** [oxheadalpha/tezos-k8s#341]
The snapshot-downloader script checks the history mode of the node to determine what snapshot/tarball it should download. The script only checks the instance level config. If no history mode is defined there, but say the mode is defined on the class level or on the global level, the script fails. `Invalid node history mode: 'null'`

**Comment by orcutt989** [comment]
Need this for https://github.com/oxheadalpha/oxheadinfra/pull/53
