### ISSUE TITLE
remove `snapshot-website-base` in snapshot engine; download it instead

### ISSUE THREAD

**Issue by nicolasochem** [oxheadalpha/tezos-k8s#416]
the _config.yml in xtz-shots-website and snapshot-website-base is identical except for one line.

Instead, let's have these 3 config in values.yaml:

```
jekyllRemoteThemeRepository: oxheadalpha/xtz-shots-website
jekyllConfig: https://raw.githubusercontent.com/oxheadalpha/xtz-shots-website/master/_config.yml
snapshotMarkdownTemplate: https://raw.githubusercontent.com/oxheadalpha/xtz-shots-website/master/snapshot.md
```

Then the website builder job:
* downloads `jekyllConfig`
* adds `remote_theme: oxheadalpha/xtz-shots-website` to the downloaded config based on the `jekyllRemoteThemeRepository` param
* uses this config to build the remote theme

**Comment by harryttd** [comment]
related to #418
