### ISSUE TITLE
config-generator.py: tezos keys should be mounted as a volume instead of env vars

### ISSUE THREAD

**Issue by nicolasochem** [oxheadalpha/tezos-k8s#432]
CIS benchmark says that [secrets should be mounted files, not env vars](https://www.tenable.com/audits/items/CIS_Kubernetes_v1.20_v1.0.0_Level_2_Master.audit:98de3da69271994afb6211cf86ae4c6b)

We are already limiting the problem by only exposing these env vars in init containers, where `config-generator.py` writes the secrets as files for octez usage, but it would be even better if we didn't use them there (and also we would pass a security audit).

**Comment by orcutt989** [comment]
https://github.com/oxheadalpha/tezos-k8s/blob/master/utils/config-generator.py#L17
it should be easy enough to replace this line with a file.open

https://github.com/oxheadalpha/tezos-k8s/blob/master/charts/tezos/templates/signer.yaml#L42-L43
and replace the above with a "volume mount from secret"
