### ISSUE TITLE
Snapshot Engine: Serve all snapshots' metadata on a single and fixed endpoint

### ISSUE THREAD

**Issue by pasqu4le** [oxheadalpha/tezos-k8s#446]
The snapshot engine currently produces [JSON metadata](https://github.com/oxheadalpha/tezos-k8s/blob/912041f605af47c812b07197218ccf5c345c37a6/charts/snapshotEngine/README.md#json) inlcuding:
> a `base.json` containing a list of all artifacts created

On `xtz-shots.io` however it seems that these are served on different URLs, depending on the network, e.g.:
- https://mainnet.xtz-shots.io/base.json
- https://ithacanet.xtz-shots.io/base.json
- etc.

but not https://xtz-shots.io/base.json

Especially in the hope of standardizing this metadata IMO it would be great if:
1. metadata for all snapshots (regardless of network) was served on a single endpoint
2. the endpoint used a fixed name, more memorable and descriptive than `base.json`

P.s. big fan of seeing this served on xtz-shots.io, we are currently trying to adopt it in [`tezos-packaging`](https://github.com/serokell/tezos-packaging).

**Comment by harryttd** [comment]
@itkach Wanted to push the prio on this
