### ISSUE TITLE
Snapshot engine: better metadata JSON format

### ISSUE THREAD

**Issue by ixahedron** [oxheadalpha/tezos-k8s#451]
The snapshot engine produces a `base.json` file with metadata of all artifacts
Each artifact-describing object currently has the following format, shown here in an example of a mainnet rolling snapshot:

```
{
  "mainnet-2371873.rolling": {
    "contents": {
      "block_hash": "BKiuhzA6fqFFMgBAhHzPvuVT9YMJhv3YfKcQQJjXt4LtPzrPUYy",
      "block_height": "2371873",
      "block_timestamp": "2022-05-17T06:09:29Z",
      "sha256": "a05006f243a8c2e8120ea3a2eaddd44ce6189cd2f67dd0a1e1446720716317c0",
      "filesize_bytes": "4398831616",
      "filesize": "4G",
      "tezos_version": "6d9cfa35 (2022-05-05 11:47:00 +0200) (12.4)",
      "chain_name": "mainnet",
      "history_mode": "rolling",
      "artifact_type": "tezos-snapshot"
    }
  }
},
```

The resulting object is multi-layered: 1. the unique name of the artifact key; 2. the single `"contents"` key; 3. various metadata keys. This makes processing this JSON programmatically more difficult for no obvious benefit. For easier standartisation/adoption it would be nice to have a more predictable format.

In particular, I'd suggest a fully flat format with predictable labels/keys for everything, including the name of the artifact. The example above would therefore have the following exemplative format:

```
{
  "filename": "mainnet-2371873.rolling",
  "block_hash": "BKiuhzA6fqFFMgBAhHzPvuVT9YMJhv3YfKcQQJjXt4LtPzrPUYy",
  "block_height": "2371873",
  "block_timestamp": "2022-05-17T06:09:29Z",
  "sha256": "a05006f243a8c2e8120ea3a2eaddd44ce6189cd2f67dd0a1e1446720716317c0",
  "filesize_bytes": "4398831616",
  "filesize": "4G",
  "tezos_version": "6d9cfa35 (2022-05-05 11:47:00 +0200) (12.4)",
  "chain_name": "mainnet",
  "history_mode": "rolling",
  "artifact_type": "tezos-snapshot"
},
```

**Comment by harryttd** [comment]
@itkach Wanted to push the prio on this

**Comment by orcutt989** [comment]
Closed with https://github.com/oxheadalpha/tezos-k8s/pull/473
