### ISSUE TITLE
Remove the DAEMON env var from nodes

### ISSUE THREAD

**Issue by harryttd** [oxheadalpha/tezos-k8s#459]
It isn't used anymore. It used to exist to determine the difference between the baker and endorser processes. Now we have just a single baker process. I found a PR where the state of the code at that time was using the env var: https://github.com/oxheadalpha/tezos-k8s/pull/117/files

Need to remove from:
https://github.com/oxheadalpha/tezos-k8s/blob/0dd8a220f2cf9bf959012e8fd6f63bc444e61699/charts/tezos/templates/_containers.tpl#L124-L125

**Comment by nicolasochem** [comment]
@elric1 uses it to customize his PS1 prompt and wants it to stay.
