### ISSUE TITLE
snapshotEngine: Generate artifact metadata in python instead of bash

### ISSUE THREAD

**Issue by orcutt989** [oxheadalpha/tezos-k8s#492]
Generating artifact metadata could be solved in a few lines of python code vs many lines of bash.

**Comment by orcutt989** [comment]
@nicolasochem I made this issue per our tech-debt discussion on how to improve zip-and-upload.

**Comment by nicolasochem** [comment]
Maybe I got the ordering wrong, it looks like the sequence is:
1. generate artifact metadata in bash, put it in artifact bucket
2. concatenate them into base.json, put it in artifact bucket
3. gather all the base.json from all artifact buckets
4. generate final artifact json and put it in the jekyll bucket

So it does not look as simple to move everything to python as I initially thought...
