### ISSUE TITLE
pre-existing activation detection misfired on Mondaynet

### ISSUE THREAD

**Issue by nicolasochem** [oxheadalpha/tezos-k8s#600]
The below logic checks that the chain has already activated and does not activate again:

https://github.com/oxheadalpha/tezos-k8s/blob/master/charts/tezos/scripts/chain-initiator.sh#L3-L12

On Sept 11 it malfunctioned, because the RPC gave a successful reply and then failed again, therefore the job failed silently.

We need to capture the answer and not do a subsequent query.

**Comment by harryttd** [comment]
closed via #601
